version: "3.9"

services:
  service1:
    build:
      context: ./service1
    ports:
      - "1024:5001"
    restart: always
    networks:
      - nodejs-network

  service2:
    build:
      context: ./service2
    ports:
      - "1025:5002"
    restart: always
    networks:
      - nodejs-network

  service3:
    build:
      context: ./service3
    ports:
      - "1026:5003"
    restart: always
    networks:
      - nodejs-network

networks:
  nodejs-network:
    driver: bridge
